server:
  port: 8280

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${postgres.hostname:localhost}:${postgres.port:5432}/prova
    driver-class-name: org.postgresql.Driver
    username: ${postgres.user:postgres}
    password: ${postgres.password:postgres}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true